"""Slide deck generation (.pptx).

Generates a slide deck summarizing the study. If ``python-pptx`` is
installed (it is a core dependency) a real .pptx file is
produced; otherwise a Markdown outline that can be imported into any slide
tool is written as a fallback. This keeps the report phase functional in
minimal environments while opening the door to richer output when the
extra is installed.
"""

from __future__ import annotations

from fastmdxplora.utils.logging import get_logger
from pathlib import Path
from typing import TYPE_CHECKING

from fastmdxplora.report.context import PhaseContext, load_phase_context

if TYPE_CHECKING:
    from fastmdxplora.orchestrator import FastMDXplora

logger = get_logger("report.slides")


def _slide_text(value: object, *, limit: int = 500) -> str:
    text = str(value)
    text = " ".join(text.replace("\t", " ").splitlines())
    text = " ".join(text.split())
    if len(text) > limit:
        return text[: limit - 1].rstrip() + "..."
    return text


def _workflow_lines(phase_context: PhaseContext) -> list[str]:
    if phase_context.is_full_pipeline:
        return [
            "Full FastMDXplora workflow: setup, simulation, analysis, and report.",
        ]
    if phase_context.is_analysis_from_existing_trajectory:
        return [
            "Analysis/report workflow from an existing trajectory.",
            "Setup and simulation were not run in this workflow.",
        ]
    lines = ["Recorded workflow phases:"]
    if phase_context.setup_present:
        lines.append("Setup phase recorded.")
    if phase_context.simulation_present:
        lines.append("Simulation phase recorded.")
    if phase_context.analysis_present:
        lines.append("Analysis phase recorded.")
    if phase_context.report_present:
        lines.append("Report phase recorded.")
    return lines


def _outline_markdown(orchestrator: "FastMDXplora", title: str) -> str:
    from fastmdxplora import __citation__, __version__

    phase_context = load_phase_context(orchestrator.output_dir)
    section_no = 1
    lines = [
        f"# {_slide_text(title)}",
        "",
        f"## {section_no}. Overview",
        f"- System: `{_slide_text(orchestrator.system)}`",
        f"- Generated by FastMDXplora v{__version__}",
    ]
    lines.extend(f"- {_slide_text(line)}" for line in _workflow_lines(phase_context))

    if phase_context.setup_present:
        section_no += 1
        lines.extend(
            [
                "",
                f"## {section_no}. Setup",
                "- See `setup/setup_parameters.json`",
            ]
        )

    if phase_context.simulation_present:
        section_no += 1
        lines.extend(
            [
                "",
                f"## {section_no}. Simulation",
                "- See `simulation/simulation_parameters.json`",
            ]
        )

    if phase_context.analysis_present:
        section_no += 1
        lines.extend(
            [
                "",
                f"## {section_no}. Analysis",
                "- See `analysis/analysis_manifest.json`",
                "- Per-analysis options in `analysis/<analysis>/options.json`",
            ]
        )

    section_no += 1
    lines.extend(["", f"## {section_no}. Citation", f"- {__citation__}", ""])
    return "\n".join(lines)


def _build_pptx(orchestrator: "FastMDXplora", title: str, out_path: Path) -> None:
    """Write a .pptx using python-pptx (called only if importable)."""
    from pptx import Presentation
    from pptx.util import Inches, Pt

    from fastmdxplora import __citation__, __version__

    prs = Presentation()
    blank = prs.slide_layouts[5]  # Title only
    title_layout = prs.slide_layouts[0]  # Title slide

    # Slide dimensions for the default layout (10 in × 7.5 in)
    slide_w = prs.slide_width
    slide_h = prs.slide_height

    # Title slide
    s = prs.slides.add_slide(title_layout)
    s.shapes.title.text = _slide_text(title)
    s.placeholders[1].text = (
        f"FastMDXplora v{__version__}\nSystem: {_slide_text(orchestrator.system)}"
    )

    def _section_slide(heading: str, body_lines: list[str]) -> None:
        slide = prs.slides.add_slide(blank)
        slide.shapes.title.text = _slide_text(heading)
        textbox = slide.shapes.add_textbox(Inches(0.5), Inches(1.5), Inches(9), Inches(5))
        tf = textbox.text_frame
        tf.word_wrap = True
        for i, line in enumerate(body_lines):
            p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            p.text = _slide_text(line, limit=700)
            p.font.size = Pt(18)

    def _image_slide(heading: str, image_path: Path, subtitle: str = "") -> None:
        """A slide that's a single titled image, centered and fit-to-slide.

        Computes a target rectangle below the title (top ~1.4 in), preserves
        the image's aspect ratio, and inserts the figure with a thin margin.
        """
        slide = prs.slides.add_slide(blank)
        slide.shapes.title.text = _slide_text(heading)

        # Optional subtitle just under the title
        if subtitle:
            sub_box = slide.shapes.add_textbox(
                Inches(0.5), Inches(1.1), slide_w - Inches(1.0), Inches(0.4)
            )
            sub_tf = sub_box.text_frame
            sub_tf.word_wrap = True
            p = sub_tf.paragraphs[0]
            p.text = _slide_text(subtitle)
            p.font.size = Pt(12)
            p.font.italic = True

        # Available region for the figure
        top = Inches(1.55)
        margin = Inches(0.3)
        avail_w = slide_w - 2 * margin
        avail_h = slide_h - top - margin

        # python-pptx will auto-size when only one dimension is given; we'd
        # rather scale ourselves to keep the figure inside the rectangle.
        from PIL import Image  # python-pptx already pulls Pillow in

        try:
            with Image.open(image_path) as im:
                img_w_px, img_h_px = im.size
            aspect = img_w_px / img_h_px
            # Fit by width first, then by height if too tall.
            target_w = avail_w
            target_h = int(avail_w / aspect)
            if target_h > avail_h:
                target_h = avail_h
                target_w = int(avail_h * aspect)
            left = (slide_w - target_w) // 2
            slide.shapes.add_picture(
                str(image_path), left, top, width=target_w, height=target_h
            )
        except Exception:  # noqa: BLE001 -- fall back to bare insert
            slide.shapes.add_picture(
                str(image_path), Inches(1.0), top, width=Inches(8.0)
            )

    project_root = orchestrator.output_dir
    phase_context = load_phase_context(project_root)

    _section_slide("Workflow", _workflow_lines(phase_context))

    if phase_context.setup_present:
        _section_slide(
            "Setup",
            [
                "System preparation phase outputs:",
                f"  • {project_root / 'setup'}",
                "Parameter manifest: setup_parameters.json",
            ],
        )
    if phase_context.simulation_present:
        _section_slide(
            "Simulation",
            [
                "Molecular dynamics simulation phase outputs:",
                f"  • {project_root / 'simulation'}",
                "Parameter manifest: simulation_parameters.json",
            ],
        )

    # Analysis: one cover slide (textual summary) + one image slide per figure
    analysis_dir = project_root / "analysis"
    manifest = _load_analysis_manifest(analysis_dir)
    plan = manifest.get("plan", [])

    if plan:
        cover_lines = [
            "Trajectory analyses performed in this session:",
        ]
        for analysis in plan:
            result = manifest.get("results", {}).get(analysis, {})
            status = result.get("status", "unknown")
            cover_lines.append(f"  • {analysis}  ({status})")
        cover_lines.append("")
        n_frames = manifest.get("n_frames")
        n_residues = manifest.get("n_residues")
        if n_frames is not None and n_residues is not None:
            cover_lines.append(
                f"Trajectory: {n_frames} frames, {n_residues} residues"
            )
        _section_slide("Analysis", cover_lines)

        # One image slide per produced figure, in plan order.
        for analysis in plan:
            sub_dir = analysis_dir / analysis
            if not sub_dir.is_dir():
                continue
            figures = sorted(sub_dir.glob("*.png"))
            for fig_path in figures:
                # Heading: analysis name in caps + a hint for multi-method
                # analyses (figure stem differs from the analysis name).
                if fig_path.stem == analysis:
                    heading = analysis.upper()
                    subtitle = ""
                else:
                    heading = analysis.upper()
                    # cluster_kmeans → "method: kmeans"
                    suffix = fig_path.stem.replace(f"{analysis}_", "", 1)
                    subtitle = f"method: {suffix}"
                _image_slide(heading, fig_path, subtitle=subtitle)
    else:
        _section_slide(
            "Analysis",
            [
                "Trajectory analysis phase outputs:",
                f"  • {project_root / 'analysis'}",
                "Manifest: analysis_manifest.json",
            ],
        )

    _section_slide(
        "Citation",
        [
            "If you use FastMDXplora in your work, please cite:",
            "",
            __citation__,
        ],
    )

    prs.save(str(out_path))


def _load_analysis_manifest(analysis_dir: Path) -> dict:
    """Read the analysis manifest if present; return {} otherwise."""
    import json

    mf = analysis_dir / "analysis_manifest.json"
    if not mf.exists():
        return {}
    try:
        with mf.open(encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, json.JSONDecodeError):
        return {}


def build_slides(
    *,
    orchestrator: "FastMDXplora",
    output_dir: Path,
    title: str,
) -> list[str]:
    """Render the slide deck.

    Returns the list of artifact paths (relative to ``output_dir``).
    """
    artifacts: list[str] = []

    # Always write the Markdown outline (no dependencies, always works).
    outline_path = output_dir / "slides_outline.md"
    outline_path.write_text(_outline_markdown(orchestrator, title), encoding="utf-8")
    artifacts.append("slides_outline.md")

    # Try to write a .pptx if python-pptx is available.
    try:
        pptx_path = output_dir / "slides.pptx"
        _build_pptx(orchestrator, title, pptx_path)
        artifacts.append("slides.pptx")
        logger.debug("slides: wrote %s", pptx_path)
    except ImportError:
        logger.debug(
            "slides: python-pptx not importable; wrote markdown outline only. "
            "python-pptx is a core dependency, so this usually means a broken "
            "install — try `pip install --force-reinstall python-pptx`."
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning("slides: pptx generation failed: %s", exc)

    return artifacts
