"""Config template generation and resolved-config dumping.

Both functions read from the schema registry so they never drift from
the actual option surface.

  - :func:`generate_template` powers ``fastmdx init-config``: a fully
    commented YAML file with every option, its default, and a one-line
    description. Users edit this rather than authoring from scratch.

  - :func:`write_resolved_config` powers the reproducibility dump: after
    a run, the fully merged configuration (defaults + file + overrides)
    is written to ``resolved_config.yml`` so the exact study can be
    re-run.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from fastmdxplora.config.schema import (
    PHASE_SCHEMAS,
    TOP_LEVEL,
    Field,
    PhaseSchema,
)


# ---------------------------------------------------------------------------
# Template generation (init-config)
# ---------------------------------------------------------------------------
def _format_value_for_yaml(value: Any) -> str:
    """Render a Python value as a YAML scalar/inline-collection string."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        # Quote strings that could be misread as YAML (e.g. 'Na+', 'name CA')
        if any(c in value for c in ":#{}[],&*!|>'\"%@` ") or value == "":
            return f'"{value}"'
        return value
    if isinstance(value, (list, tuple)):
        inner = ", ".join(_format_value_for_yaml(v) for v in value)
        return f"[{inner}]"
    if isinstance(value, dict):
        # Inline flow mapping for the example dicts in the template
        inner = ", ".join(
            f"{k}: {_format_value_for_yaml(v)}" for k, v in value.items()
        )
        return f"{{{inner}}}"
    return str(value)


def _field_template_lines(
    fld: Field, *, commented: bool, indent: int = 2
) -> list[str]:
    """Render one field as YAML lines: a help comment + the key.

    Parameters
    ----------
    fld : Field
    commented : bool
        When True, the key line is commented out (prefixed with ``# ``)
        so the template shows the option without activating it.
    indent : int
        Number of leading spaces. Top-level fields use 0; fields inside a
        phase block use 2.
    """
    pad = " " * indent
    lines = [f"{pad}# {fld.help}"]

    # The value shown: prefer the real default; fall back to the example
    # when the default is None (so the line is illustrative).
    shown = fld.default if fld.default is not None else fld.example
    value_str = _format_value_for_yaml(shown)

    if fld.default is None and fld.example is not None:
        lines[-1] += "  (default: phase default)"

    prefix = f"{pad}# " if commented else pad
    lines.append(f"{prefix}{fld.name}: {value_str}")
    return lines


def _phase_template_block(
    schema: PhaseSchema,
    *,
    commented: bool,
) -> list[str]:
    """Render a full phase block: header comment + all its fields.

    When ``commented`` is True the phase header itself is commented out
    (``# setup:``) so a fully-commented block doesn't leave a dangling
    ``setup:`` key with a null value (which would be invalid against the
    schema). The user uncomments the header and the options they want.
    """
    header_prefix = "# " if commented else ""
    lines = [
        "",
        f"# {'=' * 70}",
        f"# {schema.name}: {schema.description}",
        f"# {'=' * 70}",
        f"{header_prefix}{schema.name}:",
    ]
    for fld in schema.fields:
        lines.extend(_field_template_lines(fld, commented=commented, indent=2))
    return lines


def generate_template(*, minimal: bool = False) -> str:
    """Return a fully-commented YAML config template as a string.

    Parameters
    ----------
    minimal : bool, default False
        If True, generate a short template with only the most common
        options active. If False (default), generate the comprehensive
        template with every option shown (per-phase blocks commented out
        so defaults apply until the user opts in).
    """
    if minimal:
        return _minimal_template()

    lines: list[str] = [
        "# FastMDXplora configuration file",
        "#",
        "# Generated by `fastmdx init-config`. Every option is shown with its",
        "# default value and a one-line description. Options under each phase",
        "# block are commented out — uncomment the phase header and the options",
        "# you want to change; anything left commented uses the built-in default.",
        "#",
        "# Run with:  fastmdx explore --config this_file.yml",
        "#",
        "# Override any value from the command line — flags beat the file:",
        "#   fastmdx explore --config this_file.yml --simulate-duration-ns 50",
        "",
        "# ----------------------------------------------------------------------",
        "# Systems (REQUIRED): the list of systems to study.",
        "# Always a list — even one system goes here as a single entry. Add more",
        "# entries to study several systems in one run; each can carry its own",
        "# per-phase option overrides (e.g. a different pH).",
        "# ----------------------------------------------------------------------",
        "systems:",
        "  - id: protein1",
        "    system: protein.pdb        # PDB/CIF path, 4-char PDB ID, or sequence",
        "  # - id: protein2",
        "  #   system: 1L2Y             # a PDB ID, fetched from RCSB",
        "  #   setup: { ph: 6.5 }       # optional per-system option overrides",
        "",
        "# ----------------------------------------------------------------------",
        "# Project-level settings",
        "# ----------------------------------------------------------------------",
    ]
    # Top-level scalars (output, verbose, include, exclude) at column 0.
    for fld in TOP_LEVEL.fields:
        # `exclude` stays commented because include/exclude are exclusive
        commented = fld.name in ("exclude",)
        lines.extend(_field_template_lines(fld, commented=commented, indent=0))

    # Per-phase blocks: fully commented so the file is valid as-is
    # (everything defaults) and the user opts in to changes.
    for schema in PHASE_SCHEMAS.values():
        lines.extend(_phase_template_block(schema, commented=True))

    # Sweep + execution: optional parameter sweeps and parallelism.
    lines.extend([
        "",
        f"# {'=' * 70}",
        "# SWEEP (optional): vary parameters across runs.",
        "#",
        "# Each axis is a dotted phase.option key mapped to a list of values.",
        "# FastMDXplora runs the full cross-product (systems × sweep axes),",
        "# each as a complete study in runs/<id>/, indexed by batch_manifest.json.",
        "# With one system and no sweep you get the familiar flat output layout.",
        f"# {'=' * 70}",
        "#",
        "# sweep:",
        "#   simulation.temperature_K: [300, 310, 320]",
        "#   simulation.pressure_bar: [1.0, 1.2]   # multiple axes => cross-product",
        "",
        f"# {'=' * 70}",
        "# EXECUTION (optional): how runs are scheduled.",
        f"# {'=' * 70}",
        "#",
        "# execution:",
        "#   mode: parallel        # sequential (default) | parallel",
        "#   workers: 2            # parallel runs at once",
        "#   devices: [0, 1]       # GPU indices; one run pinned per device",
        "#   continue_on_error: true",
    ])

    return "\n".join(lines) + "\n"


def _minimal_template() -> str:
    """A short starter template with just the essentials active."""
    return (
        "# FastMDXplora configuration (minimal starter)\n"
        "# Run with:  fastmdx explore --config this_file.yml\n"
        "\n"
        "systems:\n"
        "  - id: protein1\n"
        "    system: protein.pdb      # PDB/CIF path, 4-char PDB ID, or sequence\n"
        "\n"
        "output: ./my_study\n"
        "\n"
        "simulation:\n"
        "  duration_ns: 100.0         # production length in ns\n"
        "  platform: auto             # auto | CUDA | OpenCL | CPU\n"
        "\n"
        "analysis:\n"
        "  include: [rmsd, rmsf, rg, cluster]\n"
        "\n"
        "report:\n"
        "  title: My MD Study\n"
    )


# ---------------------------------------------------------------------------
# Resolved-config dump (reproducibility)
# ---------------------------------------------------------------------------
def write_resolved_config(
    merged: dict[str, Any],
    output_dir: str | Path,
    *,
    filename: str = "resolved_config.yml",
) -> Path:
    """Write the fully-merged configuration to ``output_dir/resolved_config.yml``.

    Parameters
    ----------
    merged : dict
        The resolved run configuration. Recognized keys: ``system`` (the
        input for this run), ``system_id`` (optional id), ``output``,
        ``verbose``, ``include``, ``exclude``, and ``options`` (per-phase
        option blocks).
    output_dir : path
        Directory to write into.
    filename : str
        Output file name.

    Returns
    -------
    Path
        The path written.

    Notes
    -----
    The dump is a valid FastMDXplora config file — feed it straight back
    to ``--config`` to reproduce the run. The single system is written as
    the canonical one-element ``systems:`` list. Only set (non-None)
    values are written so the file stays readable.
    """
    import yaml

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    # Reassemble into config-file shape (canonical `systems:` list).
    doc: dict[str, Any] = {}
    if merged.get("system") is not None:
        sid = merged.get("system_id") or "s1"
        doc["systems"] = [{"id": sid, "system": str(merged["system"])}]
    if merged.get("output") is not None:
        doc["output"] = str(merged["output"])
    if merged.get("verbose"):
        doc["verbose"] = bool(merged["verbose"])
    if merged.get("include"):
        doc["include"] = list(merged["include"])
    if merged.get("exclude"):
        doc["exclude"] = list(merged["exclude"])

    options = merged.get("options") or {}
    for phase, block in options.items():
        if block:
            doc[phase] = dict(block)

    header = (
        "# FastMDXplora resolved configuration\n"
        "#\n"
        "# This is the fully-merged configuration actually used for this run\n"
        "# (built-in defaults + config file + command-line overrides). Feed it\n"
        "# back to reproduce the exact study:\n"
        "#\n"
        "#   fastmdx explore --config resolved_config.yml\n"
        "#\n"
    )
    path = out / filename
    with path.open("w", encoding="utf-8") as fh:
        fh.write(header)
        yaml.safe_dump(doc, fh, sort_keys=False, default_flow_style=False)
    return path
